# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='planserver.proto',
  package='planserver',
  syntax='proto3',
  serialized_options=_b('\n\026io.grpc.examples.cronsB\017taskserverProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x10planserver.proto\x12\nplanserver\">\n\x0bPlanRequest\x12\x0f\n\x07\x63ronsId\x18\x01 \x01(\t\x12\r\n\x05times\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"!\n\x0ePlanDelRequest\x12\x0f\n\x07\x63ronsId\x18\x01 \x01(\t\"*\n\tPlanReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf7\x01\n\x04Plan\x12\x37\n\x03set\x12\x17.planserver.PlanRequest\x1a\x15.planserver.PlanReply\"\x00\x12:\n\x06update\x12\x17.planserver.PlanRequest\x1a\x15.planserver.PlanReply\"\x00\x12=\n\x06\x64\x65lete\x12\x1a.planserver.PlanDelRequest\x1a\x15.planserver.PlanReply\"\x00\x12;\n\x04read\x12\x1a.planserver.PlanDelRequest\x1a\x15.planserver.PlanReply\"\x00\x42\x31\n\x16io.grpc.examples.cronsB\x0ftaskserverProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_PLANREQUEST = _descriptor.Descriptor(
  name='PlanRequest',
  full_name='planserver.PlanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cronsId', full_name='planserver.PlanRequest.cronsId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='times', full_name='planserver.PlanRequest.times', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='planserver.PlanRequest.command', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=94,
)


_PLANDELREQUEST = _descriptor.Descriptor(
  name='PlanDelRequest',
  full_name='planserver.PlanDelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cronsId', full_name='planserver.PlanDelRequest.cronsId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=129,
)


_PLANREPLY = _descriptor.Descriptor(
  name='PlanReply',
  full_name='planserver.PlanReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='planserver.PlanReply.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='planserver.PlanReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['PlanRequest'] = _PLANREQUEST
DESCRIPTOR.message_types_by_name['PlanDelRequest'] = _PLANDELREQUEST
DESCRIPTOR.message_types_by_name['PlanReply'] = _PLANREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlanRequest = _reflection.GeneratedProtocolMessageType('PlanRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLANREQUEST,
  __module__ = 'planserver_pb2'
  # @@protoc_insertion_point(class_scope:planserver.PlanRequest)
  ))
_sym_db.RegisterMessage(PlanRequest)

PlanDelRequest = _reflection.GeneratedProtocolMessageType('PlanDelRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLANDELREQUEST,
  __module__ = 'planserver_pb2'
  # @@protoc_insertion_point(class_scope:planserver.PlanDelRequest)
  ))
_sym_db.RegisterMessage(PlanDelRequest)

PlanReply = _reflection.GeneratedProtocolMessageType('PlanReply', (_message.Message,), dict(
  DESCRIPTOR = _PLANREPLY,
  __module__ = 'planserver_pb2'
  # @@protoc_insertion_point(class_scope:planserver.PlanReply)
  ))
_sym_db.RegisterMessage(PlanReply)


DESCRIPTOR._options = None

_PLAN = _descriptor.ServiceDescriptor(
  name='Plan',
  full_name='planserver.Plan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=176,
  serialized_end=423,
  methods=[
  _descriptor.MethodDescriptor(
    name='set',
    full_name='planserver.Plan.set',
    index=0,
    containing_service=None,
    input_type=_PLANREQUEST,
    output_type=_PLANREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='planserver.Plan.update',
    index=1,
    containing_service=None,
    input_type=_PLANREQUEST,
    output_type=_PLANREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='planserver.Plan.delete',
    index=2,
    containing_service=None,
    input_type=_PLANDELREQUEST,
    output_type=_PLANREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='planserver.Plan.read',
    index=3,
    containing_service=None,
    input_type=_PLANDELREQUEST,
    output_type=_PLANREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAN)

DESCRIPTOR.services_by_name['Plan'] = _PLAN

# @@protoc_insertion_point(module_scope)
