# Generated by Django 2.2 on 2019-04-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crons', '0004_task_host_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('createtime', models.DateTimeField(verbose_name='create time')),
                ('isdelete', models.IntegerField(default=0)),
            ],
        ),
    ]
