# Generated by Django 2.2 on 2019-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crons', '0005_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('host_id', models.IntegerField()),
                ('createtime', models.DateTimeField(verbose_name='create time')),
            ],
        ),
    ]
